name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Format
        run: pnpm run format

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          # TODO: GPG sign: https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#signing-commits
          commit_message: "[skip ci] style: format code with prettier"
