name: PR Build Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Build Check
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build Development Version
        run: |
          chmod +x build.sh
          ./build.sh --dev --no-compress
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          # OPENLIST_FRONTEND_BUILD_MODE: dev
          # OPENLIST_FRONTEND_BUILD_COMPRESS: false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Long-Cloud-dist-dev-${{ github.sha }}
          path: dist/
          retention-days: 7